### ISSUE TITLE
[Bug] Output file not randomised

### ISSUE THREAD

**Issue by CraigRichSmith** [SilverstarStream/pokemon-entrance-randomizer#2]
**Describe the bug**
A clear and concise description of what the bug is. MacOSx Catalina, application opens via double click on the jar file, can't open via command prompt. Rom loads fine, saves fine but the output file is not randomised. 

**To Reproduce**
1. Go to load roam
2. Click on pokemon platinum 
3. Check randomise map
4. Save
5. Open output file
6. Loaded rom is not randomised 

**Expected behavior**
A clear and concise description of what you expected to happen. Load zones and other edits remain the same as the original rom. 

**System (please complete the following information):**
 - Operating System: mac os catalina 10.15
 - Java Version: 
 - Randomizer Version: 0.1.1b

**Additional context**

**Comment by wallabros** [comment]
how did you fix this?
